name: Publish

env:
  NUGET_OUTPUT: ./Artifacts/NuGet

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release
        id: release
        uses: cratis/release-action@v1
        with:
          user-name: 'Cratis Build'
          user-email: 'build@cratis.io'

      - name: Build & push the Docker image
        run: |
          docker login -u $\{{ secrets.DOCKER_USERNAME }} --password-stdin $\{{ env.DOCKER_REGISTRY }}
          docker build . --file ./Source/Main/Dockerfile --tag einari/dyslexia:$\{{ steps.release.outputs.version }}
          docker push einari/dyslexia:$\{{ steps.release.outputs.version }}
