name: Publish

env:
  NUGET_OUTPUT: ./Artifacts/NuGet

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release
        id: release
        uses: cratis/release-action@v1
        with:
          user-name: 'Cratis Build'
          user-email: 'build@cratis.io'

      - name: Build & push the Docker image
        run: |
          echo $\{{ secrets.REGISTRY_PASSWORD }} | docker login -u $\{{ secrets.REGISTRY_USERNAME }} --password-stdin $\{{ env.CONTAINER_REGISTRY }}
          docker build . --file $\{{ github.event.inputs.dockerfile }} --tag einari/dyslexia:$\{{ github.event.inputs.version }}
          docker push einari/dyslexia:$\{{ steps.release.outputs.version }}
